apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  annotations:
    meta.crossplane.io/maintainer: Daniel Vaskivaara <daniel.vaskivaara@eficode.com>
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      An introductory example to Crossplane and a Composition for the official Upbound AWS provider.
    meta.crossplane.io/readme: |
      An introductory example to Crossplane and a Composition for the official Upbound AWS provider.
      This will enable provisioning of an S3 bucket
    provider: aws
  name: hello-bucket
spec:
  crossplane:
    version: ">=v1.11.3-up.1"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-aws
      version: ">=v0.34.0"